### ISSUE TITLE
Does not listen on IPv6

### ISSUE THREAD

**Issue by bentogoa** [all-knowing-dns/all-knowing-dns#2]
Please see if you can patch it.

**Comment by stapelberg** [comment]
How ironic, given the purpose of the program :)

I don’t use all-knowing-dns, so I’ll have to rely on a pull request for this feature.

Thanks for understanding,

**Comment by bentogoa** [comment]
Thanks for your quick response.

I found the problem, Net::DNS::Nameserver  needs IO::Socket::IP to listen on ipv6.
